# Generated by Django 4.1.5 on 2023-07-17 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies_module', '0001_initial'),
        ('cinema_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('price', models.IntegerField(default=20000)),
                ('free_seats', models.IntegerField()),
                ('salable_seats', models.IntegerField()),
                ('status', models.CharField(choices=[(1, 'sale not started'), (2, 'sale open'), (3, 'tickets sold'), (4, 'sale closed'), (5, 'movie played'), (6, 'show canceled')], max_length=100)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_module.cinema')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_module.movie')),
            ],
        ),
    ]
