# Generated by Django 4.1.5 on 2023-07-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_user_address_user_birth_date_user_gender_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
